[tool.poetry]
name = "test"
version = "1.1.0"
description = "test"
authors = []

[tool.poetry.dependencies]
flask = "1.0.2"

[build-system]
requires = ["poetry>=1.0.2"]
build-backend = "poetry.masonry.api"
